import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "textbook",
      items: [
        {
          type: "category",
          label: "appendices",
          items: ['textbook/appendices/module-progression'],
        },
        {
          type: "category",
          label: "assets",
          items: [
            {
              type: "category",
              label: "code-examples",
              items: [
                {
                  type: "category",
                  label: "01",
                  items: ["textbook/assets/code-examples/01/README"]
                },
              ],
            },
            {
              type: "category",
              label: "diagrams",
              items: ["textbook/assets/diagrams/README"]  
            },
            {
              type: "category",
              label: "robot-models",
              items: [
                {
                  type: "category",
                  label: "gazebo",
                  items: ["textbook/assets/robot-models/gazebo/README"]
                }, 
                {
                  type: "category",
                  label: "mujoco",
                  items: ["textbook/assets/robot-models/mujoco/README"]
                }, 
              ],
            },]
        },
        {
          type: "category",
          label: "case-studies",
          items: [
            {
              type: "autogenerated",
              dirName: "textbook/case-studies"
            }
          ],
        },
        {
          type: "category",
          label: "modules",
          items: [
            {
              type: "autogenerated",
              dirName: "textbook/modules"
            }
          ]
        },
      ],
    },
  ],
};

export default sidebars;
